### PR TITLE
Add basic MHC nomenclature parsing

### PR DESCRIPTION
**Pull request by rleonid**

### CODE REVIEW

**Comment by hammer** [comment]
Any chance we could share tests with https://github.com/hammerlab/mhcnames somehow (cc @iskandr)? We recently had a bug report w/ our handling of numbers > 100, for example, and it would be nice if a Python bug was fixed in OCaml, and vice versa.

**Comment by iskandr** [comment]
I would strongly discourage parsing MHC nomenclature unless you really have to normalize between different sources. I still have a bunch of outstanding issues on `mhcnames` because the conventions differ between species.

**Comment by iskandr** [comment]
Though, if the "HLA" in prohlatype implies that this is only meant for human data then you only have to parse Class I vs. Class II human alleles, which is a simpler problem.

**Comment by rleonid** [comment]
@hammer This is meant as an internal (to prohlatype) code. I'm not trying to parse any other formats besides [imgt](http://hla.alleles.org/nomenclature/naming.html)'s (and even there, I'm implicitly absorbing the 'HLA'), nor am I trying to compact names. 

@iskandr  I don't need to normalize between different sources, I just want to compare based on resolution.

**Pull request merged**
