### PR TITLE
Add a `Dockerfile` #WIP

### PR DESCRIPTION
**Pull request by smondet**
Not yet ready, I'm adding some more things.

### CODE REVIEW

**Comment by smondet** [comment]
Automated build: https://hub.docker.com/r/hammerlab/prohlatype/builds/

**Comment by smondet** [comment]
image

**Comment by rleonid** [comment]
Cool, so I'll extend this with the relevant build and test commands.

**Comment by smondet** [comment]
Also, building like this:

```
 docker build -t prohlatype:test .
 ```
 
Works at least for `--version`:

```
 $ docker run prohlatype:test _build/src/app/par_type.native --version
0.0.0
 $ docker run prohlatype:test _build/src/app/align2fasta.native --version
0.0.0
 $ docker run prohlatype:test _build/src/app/mhc2gpdf.native --version
0.0.0
 $ docker run prohlatype:test _build/src/app/mpjson2tsv.native --version
0.0.0
 $ docker run prohlatype:test _build/src/app/multi_par.native --version
0.0.0
```

@rleonid do you prefer to merge this (just the dockerfile) and then, when docker-hub has built the `master`/`latest` version,  I'll do a PR on the `README.md` for instructions? or do you prefer "speculative" instructions now?

**Comment by smondet** [comment]
Oh wait forgot to integrate previous PR that got merged.

Now `make setup` fails because it depends on `opam` ≥ 2 ?

```
opam install --deps-only ./prohlatype.opam
opam: PACKAGES... arguments: Invalid character . in package name
      "./prohlatype.opam"
Usage: opam install [OPTION]... PACKAGES...
Try `opam install --help' or `opam --help' for more information.
Makefile:9: recipe for target 'setup' failed
make: *** [setup] Error 1
The command '/bin/sh -c make setup' returned a non-zero code: 2
```

**Comment by rleonid** [comment]
Yea, I made the switch to opam v2 on my mac and now (regrettably) I have to support 2 opam versions?

**Comment by smondet** [comment]
@rleonid as you prefer, I changed the `Dockerfile` to not use `make setup` and it builds fine.

**Comment by smondet** [comment]
Is this expected with the opam-pin-installed binaries?
```
 $ docker run prohlatype:test par_type --version
%%VERSION%%
```

**Comment by rleonid** [comment]
No, I'm trying to figure out why it seems like the (not in stable documentation) `jbuilder subst`command is not running?

**Comment by rleonid** [comment]
I'll merge the dockerfile when i figure out these last set of issues.

**Comment by rleonid** [comment]
@smondet I've merged in manually https://github.com/hammerlab/prohlatype/commit/86a00366503313d57b22cd58209360beefde8a54

**Pull request closed without merging**
